#encrypt.key: ${ENCRYPT_KEY:Cvo7HWIiDUvK}
server:
  port: 8082
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: resource
          uri: lb://RESOURCE-SERVICE/api/resource-server
          predicates:
            - Path=/api/resource-server/**
        - id: auth
          uri: lb://AUTH-SERVICE/auth
          predicates:
            - Path=/auth/**
        #Always last!
        - id: site
          uri: ${MAIN-SITE:http://localhost:8080}
          predicates:
            - Path=/**,/**.js,/**.html,/**.css
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8082/auth/realms/scaks}
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8082/auth/realms/scaks/protocol/openid-connect/certs}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:eureka_user}:${EUREKA_PASSWORD:ENC(LLKDrDlcr1JyW6SHjzSEthj4R3Ggww4I9ar/YF/vwBWUXfwmw8xfTSt8BRmAFWCu)}@${EUREKA_SERVER_HOST:localhost:8761}/eureka
# Enable these to debug the Authorization flow
#logging:
#  level:
#    org:
#      springframework:
#        security:
#          web: DEBUG
management:
  endpoint:
    health:
      showDetails: always
  endpoints:
    web:
      exposure:
        include: "*"
jasypt:
  encryptor:
    password: ${JASYPT_SECRET:scaks-jasypt-password}
