#encrypt.key: ${ENCRYPT_KEY:Cvo7HWIiDUvK}
server:
  port: ${AUTH_SERVER_PORT:8282}

spring:
  application:
    name: auth-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: ${KC_DB_URL:jdbc:h2:file:./test;DB_CLOSE_ON_EXIT=FALSE}
    username: ${KC_DB_USER:sa}
    password: ${KC_DB_PASSWORD:}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:eureka_user}:${EUREKA_PASSWORD:ENC(LLKDrDlcr1JyW6SHjzSEthj4R3Ggww4I9ar/YF/vwBWUXfwmw8xfTSt8BRmAFWCu)}@${EUREKA_SERVER_HOST:localhost:8761}/eureka
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
jasypt:
  encryptor:
    password: ${JASYPT_SECRET:scaks-jasypt-password}