#encrypt.key: ${ENCRYPT_KEY:Cvo7HWIiDUvK}
server:
  port: 8761

#encrypt.key: ${ENCRYPT_KEY:Cvo7HWIiDUvK}

spring:
  boot:
    admin:
      context-path: /admin
  application:
    name: admin-service
  security:
    user:
      name: ${EUREKA_USERNAME:eureka_user}
      password: ${EUREKA_PASSWORD:ENC(LLKDrDlcr1JyW6SHjzSEthj4R3Ggww4I9ar/YF/vwBWUXfwmw8xfTSt8BRmAFWCu)}
eureka:
  instance:
    preferIpAddress: true
    #     to allow SBA access this service
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${EUREKA_SERVER_HOST:localhost:8761}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
jasypt:
  encryptor:
    password: ${JASYPT_SECRET:scaks-jasypt-password}
